<a href="https://colab.research.google.com/github/matte0-0/DCS-210/blob/main/proj2_Hotel_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project 2: Hotel Data

by Matteo Pagano

for DCS 210: Programming for Data Analysis and Visualization

In [1]:
install.packages("tidyverse")
install.packages("skimr")

library(tidyverse)
library(skimr)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.3.6      ✔ purrr   0.3.4
✔ tibble  3.1.7      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1
✔ readr   2.1.2      ✔ forcats 0.5.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
# hotels.csv file manually uploaded into Colab file store first
hotels <- read.csv("hotels.csv")

## Question 1

**Q1.** Run the following command: `skim(hotels)`. What information does this provide you and how does it aid with your analysis?

**A1.** The `skim` command provides both a general overview of the shape of the data passed into it and a more indepth summary of every variable, categorized by variable type. For the purposes of this analysis, the skim command's neat organization of the character and numeric variables are very helpful.

In [3]:
skim(hotels)

── Data Summary ────────────────────────
                           Values
Name                       hotels
Number of rows             119390
Number of columns          32
_______________________
Column type frequency:
  character                14
  numeric                  18
________________________
Group variables            None

── Variable type: character ────────────────────────────────────────────────────
   skim_variable           n_missing complete_rate min max empty n_unique
 1 hotel                           0             1  10  12     0        2
 2 arrival_date_month              0             1   3   9     0       12
 3 meal                            0             1   2   9     0        5
 4 country                         0             1   2   4     0      178
 5 market_segment                  0             1   6  13     0        8
 6 distribution_channel            0             1   3   9     0        5
 7 reserved_room_type              0             1   1   1     0       10
 8 assigned_room_type              0             1   1   1     0       12
 9 deposit_type                    0             1  10  10     0        3
10 agent                           0             1   1   4     0      334
11 company                         0             1   1   4     0      353
12 customer_type                   0             1   5  15     0        4
13 reservation_status              0             1   7   9     0        3
14 reservation_status_date         0             1  10  10     0      926
   whitespace
 1          0
 2          0
 3          0
 4          0
 5          0
 6          0
 7          0
 8          0
 9          0
10          0
11          0
12          0
13          0
14          0

── Variable type: numeric ──────────────────────────────────────────────────────
   skim_variable                  n_missing complete_rate       mean       sd
 1 is_canceled                            0          1       0.370     0.483
 2 lead_time                              0          1     104.      107.
 3 arrival_date_year                      0          1    2016.        0.707
 4 arrival_date_week_number               0          1      27.2      13.6
 5 arrival_date_day_of_month              0          1      15.8       8.78
 6 stays_in_weekend_nights                0          1       0.928     0.999
 7 stays_in_week_nights                   0          1       2.50      1.91
 8 adults                                 0          1       1.86      0.579
 9 children                               4          1.00    0.104     0.399
10 babies                                 0          1       0.00795   0.0974
11 is_repeated_guest                      0          1       0.0319    0.176
12 previous_cancellations                 0          1       0.0871    0.844
13 previous_bookings_not_canceled         0          1       0.137     1.50
14 booking_changes                        0          1       0.221     0.652
15 days_in_waiting_list                   0          1       2.32     17.6
16 adr                                    0          1     102.       50.5
17 required_car_parking_spaces            0          1       0.0625    0.245
18 total_of_special_requests              0          1       0.571     0.793
        p0    p25    p50  p75 p100 hist
 1    0       0      0      1    1 ▇▁▁▁▅
 2    0      18     69    160  737 ▇▂▁▁▁
 3 2015    2016   2016   2017 2017 ▃▁▇▁▆
 4    1      16     28     38   53 ▅▇▇▇▅
 5    1       8     16     23   31 ▇▇▇▇▆
 6    0       0      1      2   19 ▇▁▁▁▁
 7    0       1      2      3   50 ▇▁▁▁▁
 8    0       2      2      2   55 ▇▁▁▁▁
 9    0       0      0      0   10 ▇▁▁▁▁
10    0       0      0      0   10 ▇▁▁▁▁
11    0       0      0      0    1 ▇▁▁▁▁
12    0       0      0      0   26 ▇▁▁▁▁
13    0       0      0      0   72 ▇▁▁▁▁
14    0       0      0      0   21 ▇▁▁▁▁
15    0       0      0      0  391 ▇▁▁▁▁
16   -6.38   69.3   94.6  126 5400 ▇▁▁▁▁
17    0       0      0      0    8 ▇▁▁▁▁
18    0       0      0      1    5 ▇▁▁▁▁

Warning message in is.null(text_repr) || nchar(text_repr) == 0L:
“'length(x) = 2 > 1' in coercion to 'logical(1)'”

## Question 2

**Q2.** Starting with the base data pipe to a filter and remove all guests from the US (country code "USA") and find the lead_time of less than 1 day. What command does this? What information does this filter provide?

**A2.** The below command filters the base data to the desired subset. This filter focuses in on the 6174 observed bookings which are from outside the US and were booked within a day of its start.

In [4]:
hotels %>%
  filter(country != "USA", lead_time < 1)

     hotel        is_canceled lead_time arrival_date_year arrival_date_month
1    Resort Hotel 0           0         2015              July
2    Resort Hotel 0           0         2015              July
3    Resort Hotel 0           0         2015              July
4    Resort Hotel 0           0         2015              July
5    Resort Hotel 0           0         2015              July
6    Resort Hotel 0           0         2015              July
7    Resort Hotel 0           0         2015              July
8    Resort Hotel 0           0         2015              July
9    Resort Hotel 0           0         2015              July
10   Resort Hotel 0           0         2015              July
11   Resort Hotel 0           0         2015              July
12   Resort Hotel 0           0         2015              July
13   Resort Hotel 0           0         2015              July
14   Resort Hotel 0           0         2015              July
15   Resort Hotel 0           0         2015              July
16   Resort Hotel 0           0         2015              July
17   Resort Hotel 0           0         2015              July
18   Resort Hotel 0           0         2015              July
19   Resort Hotel 0           0         2015              July
20   Resort Hotel 0           0         2015              July
21   Resort Hotel 0           0         2015              July
22   Resort Hotel 1           0         2015              July
23   Resort Hotel 0           0         2015              July
24   Resort Hotel 1           0         2015              July
25   Resort Hotel 0           0         2015              July
26   Resort Hotel 0           0         2015              July
27   Resort Hotel 0           0         2015              July
28   Resort Hotel 0           0         2015              July
29   Resort Hotel 0           0         2015              July
30   Resort Hotel 0           0         2015              July
⋮    ⋮            ⋮           ⋮         ⋮                 ⋮
6145 City Hotel   0           0         2017              August
6146 City Hotel   0           0         2017              August
6147 City Hotel   0           0         2017              August
6148 City Hotel   0           0         2017              August
6149 City Hotel   0           0         2017              August
6150 City Hotel   0           0         2017              August
6151 City Hotel   0           0         2017              August
6152 City Hotel   0           0         2017              August
6153 City Hotel   0           0         2017              August
6154 City Hotel   0           0         2017              August
6155 City Hotel   0           0         2017              August
6156 City Hotel   0           0         2017              August
6157 City Hotel   0           0         2017              August
6158 City Hotel   0           0         2017              August
6159 City Hotel   0           0         2017              August
6160 City Hotel   0           0         2017              August
6161 City Hotel   0           0         2017              August
6162 City Hotel   0           0         2017              August
6163 City Hotel   0           0         2017              August
6164 City Hotel   0           0         2017              August
6165 City Hotel   0           0         2017              August
6166 City Hotel   0           0         2017              August
6167 City Hotel   0           0         2017              August
6168 City Hotel   0           0         2017              August
6169 City Hotel   0           0         2017              August
6170 City Hotel   0           0         2017              August
6171 City Hotel   0           0         2017              August
6172 City Hotel   0           0         2017              August
6173 City Hotel   0           0         2017              August
6174 City Hotel   0           0         2017              August
     arrival_date_week_number arrival_date_day_of_month stays_in_weekend_nights
1    27                        1                        0
2    27                        1                        0
3    27                        2                        0
4    27                        2                        0
5    27                        2                        0
6    28                        5                        1
7    28                        6                        0
8    28                        7                        0
9    28                        7                        0
10   28                        7                        0
11   28                        7                        0
12   28                        8                        0
13   28                       11                        0
14   28                       11                        0
15   28                       11                        0
16   28                       11                        0
17   29                       13                        1
18   29                       13                        1
19   29                       13                        1
20   29                       14                        0
21   29                       14                        0
22   29                       16                        0
23   29                       16                        0
24   29                       17                        0
25   29                       18                        0
26   30                       19                        1
27   30                       19                        1
28   30                       19                        1
29   30                       20                        0
30   30                       20                        0
⋮    ⋮                        ⋮                         ⋮
6145 34                       20                        1
6146 34                       20                        1
6147 33                       17                        1
6148 33                       19                        1
6149 34                       20                        2
6150 34                       21                        1
6151 34                       22                        0
6152 34                       21                        1
6153 33                       19                        2
6154 34                       23                        0
6155 34                       24                        0
6156 34                       24                        0
6157 34                       25                        0
6158 34                       26                        0
6159 35                       27                        1
6160 35                       27                        1
6161 35                       27                        1
6162 35                       27                        1
6163 35                       27                        1
6164 35                       27                        1
6165 35                       28                        1
6166 35                       29                        0
6167 35                       28                        1
6168 35                       28                        1
6169 35                       29                        0
6170 35                       29                        0
6171 34                       23                        2
6172 35                       29                        0
6173 35                       30                        0
6174 35                       29                        0
     stays_in_week_nights adults ⋯ deposit_type agent company
1    2                    2      ⋯ No Deposit   NULL  NULL
2    1                    2      ⋯ No Deposit   NULL  110
3    1                    2      ⋯ No Deposit   NULL  NULL
4    1                    2      ⋯ No Deposit   240   NULL
5    1                    2      ⋯ No Deposit   NULL  NULL
6    0                    2      ⋯ No Deposit   306   NULL
7    0                    1      ⋯ No Deposit   250   NULL
8    1                    1      ⋯ No Deposit   240   NULL
9    1                    3      ⋯ No Deposit   NULL  NULL
10   1                    1      ⋯ No Deposit   240   NULL
11   4                    2      ⋯ No Deposit   NULL  NULL
12   1                    1      ⋯ No Deposit   146   NULL
13   1                    1      ⋯ No Deposit   NULL  NULL
14   1                    2      ⋯ No Deposit   240   NULL
15   1                    2      ⋯ No Deposit   NULL  NULL
16   1                    2      ⋯ No Deposit   240   NULL
17   1                    2      ⋯ No Deposit   240   NULL
18   1                    4      ⋯ No Deposit   NULL  NULL
19   3                    1      ⋯ No Deposit   167   NULL
20   4                    2      ⋯ No Deposit   240   NULL
21   1                    1      ⋯ No Deposit   NULL  NULL
22   1                    2      ⋯ No Deposit   241   NULL
23   2                    2      ⋯ No Deposit   NULL  NULL
24   1                    2      ⋯ No Deposit   NULL  NULL
25   1                    2      ⋯ No Deposit   NULL  NULL
26   0                    2      ⋯ No Deposit   NULL  NULL
27   0                    2      ⋯ No Deposit   240   NULL
28   0                    2      ⋯ No Deposit   NULL  240
29   0                    1      ⋯ No Deposit   5     NULL
30   0                    2      ⋯ No Deposit   241   NULL
⋮    ⋮                    ⋮      ⋱ ⋮            ⋮     ⋮
6145 0                    1      ⋯ No Deposit   98    NULL
6146 0                    3      ⋯ No Deposit   NULL  NULL
6147 3                    2      ⋯ No Deposit   9     NULL
6148 1                    2      ⋯ No Deposit   152   NULL
6149 0                    1      ⋯ No Deposit   98    NULL
6150 0                    2      ⋯ No Deposit   9     NULL
6151 1                    2      ⋯ No Deposit   14    NULL
6152 1                    2      ⋯ No Deposit   9     NULL
6153 4                    2      ⋯ No Deposit   98    NULL
6154 2                    1      ⋯ No Deposit   98    NULL
6155 1                    2      ⋯ No Deposit   NULL  NULL
6156 1                    2      ⋯ No Deposit   9     NULL
6157 2                    1      ⋯ No Deposit   6     NULL
6158 1                    2      ⋯ No Deposit   NULL  NULL
6159 0                    2      ⋯ No Deposit   9     NULL
6160 0                    2      ⋯ No Deposit   9     NULL
6161 0                    2      ⋯ No Deposit   9     NULL
6162 0                    2      ⋯ No Deposit   9     NULL
6163 0                    2      ⋯ No Deposit   9     NULL
6164 0                    1      ⋯ No Deposit   NULL  NULL
6165 0                    2      ⋯ No Deposit   9     NULL
6166 1                    2      ⋯ No Deposit   229   NULL
6167 0                    2      ⋯ No Deposit   9     NULL
6168 0                    2      ⋯ No Deposit   14    NULL
6169 1                    1      ⋯ No Deposit   NULL  72
6170 1                    2      ⋯ No Deposit   9     NULL
6171 5                    2      ⋯ No Deposit   394   NULL
6172 1                    2      ⋯ No Deposit   NULL  NULL
6173 1                    1      ⋯ No Deposit   NULL  NULL
6174 3                    2      ⋯ No Deposit   9     NULL
     days_in_waiting_list customer_type   adr    required_car_parking_spaces
1    0                    Transient       107.00 0
2    0                    Transient       107.42 0
3    0                    Transient       147.00 0
4    0                    Transient       117.90 0
5    0                    Transient       123.00 0
6    0                    Transient        85.10 0
7    0                    Transient         0.00 0
8    0                    Transient       109.80 0
9    0                    Transient       195.00 1
10   0                    Transient       109.80 0
11   0                    Transient        98.00 0
12   0                    Transient        61.00 0
13   0                    Transient       123.00 0
14   0                    Transient       144.90 0
15   0                    Transient       153.00 0
16   0                    Transient       131.00 0
17   0                    Transient       117.90 1
18   0                    Transient       150.00 0
19   0                    Transient       114.00 0
20   0                    Transient       111.15 0
21   0                    Transient       134.00 0
22   0                    Transient       123.20 0
23   0                    Transient       198.00 1
24   0                    Transient       136.00 0
25   0                    Transient       249.00 0
26   0                    Transient        98.00 0
27   0                    Group            98.00 1
28   0                    Group            88.20 0
29   0                    Transient         0.00 0
30   0                    Transient         0.00 0
⋮    ⋮                    ⋮               ⋮      ⋮
6145 0                    Transient-Party 115.0  0
6146 0                    Transient       198.0  0
6147 0                    Transient       143.1  0
6148 0                    Transient       110.7  0
6149 0                    Transient-Party 115.0  0
6150 0                    Transient       198.0  0
6151 0                    Transient       195.0  0
6152 0                    Transient       140.0  0
6153 0                    Transient-Party 125.0  0
6154 0                    Transient-Party 115.0  0
6155 0                    Transient       148.0  0
6156 0                    Transient       128.0  0
6157 0                    Transient-Party  95.5  0
6158 0                    Transient       200.0  0
6159 0                    Transient        80.1  0
6160 0                    Transient        89.0  0
6161 0                    Transient        99.0  0
6162 0                    Transient        80.1  0
6163 0                    Transient       116.1  0
6164 0                    Transient        95.0  0
6165 0                    Transient       140.0  0
6166 0                    Group           270.0  0
6167 0                    Transient       140.0  0
6168 0                    Transient       150.0  0
6169 0                    Transient         0.0  0
6170 0                    Transient       140.0  0
6171 0                    Transient       112.1  0
6172 0                    Transient       270.0  0
6173 0                    Transient       140.0  0
6174 0                    Transient       135.0  0
     total_of_special_requests reservation_status reservation_status_date
1    0                         Check-Out          2015-07-03
2    0                         Check-Out          2015-07-02
3    0                         Check-Out          2015-07-03
4    2                         Check-Out          2015-07-03
5    0                         Check-Out          2015-07-03
6    0                         Check-Out          2015-07-06
7    0                         Check-Out          2015-07-06
8    3                         Check-Out          2015-07-08
9    0                         Check-Out          2015-07-08
10   3                         Check-Out          2015-07-08
11   0                         Check-Out          2015-07-11
12   0                         Check-Out          2015-07-09
13   0                         Check-Out          2015-07-12
14   1                         Check-Out          2015-07-12
15   0                         Check-Out          2015-07-12
16   1                         Check-Out          2015-07-12
17   0                         Check-Out          2015-07-15
18   0                         Check-Out          2015-07-15
19   0                         Check-Out          2015-07-17
20   1                         Check-Out          2015-07-18
21   0                         Check-Out          2015-07-15
22   0                         Canceled           2015-07-16
23   0                         Check-Out          2015-07-18
24   0                         Canceled           2015-07-17
25   0                         Check-Out          2015-07-19
26   0                         Check-Out          2015-07-20
27   0                         Check-Out          2015-07-20
28   0                         Check-Out          2015-07-20
29   0                         Check-Out          2015-07-20
30   1                         Check-Out          2015-07-20
⋮    ⋮                         ⋮                  ⋮
6145 0                         Check-Out          2017-08-21
6146 0                         Check-Out          2017-08-21
6147 1                         Check-Out          2017-08-21
6148 0                         Check-Out          2017-08-21
6149 0                         Check-Out          2017-08-22
6150 0                         Check-Out          2017-08-22
6151 1                         Check-Out          2017-08-23
6152 2                         Check-Out          2017-08-23
6153 0                         Check-Out          2017-08-25
6154 0                         Check-Out          2017-08-25
6155 1                         Check-Out          2017-08-25
6156 1                         Check-Out          2017-08-25
6157 1                         Check-Out          2017-08-27
6158 0                         Check-Out          2017-08-27
6159 1                         Check-Out          2017-08-28
6160 2                         Check-Out          2017-08-28
6161 1                         Check-Out          2017-08-28
6162 1                         Check-Out          2017-08-28
6163 0                         Check-Out          2017-08-28
6164 0                         Check-Out          2017-08-28
6165 1                         Check-Out          2017-08-29
6166 1                         Check-Out          2017-08-30
6167 2                         Check-Out          2017-08-29
6168 0                         Check-Out          2017-08-29
6169 2                         Check-Out          2017-08-30
6170 0                         Check-Out          2017-08-30
6171 0                         Check-Out          2017-08-30
6172 0                         Check-Out          2017-08-30
6173 0                         Check-Out          2017-08-31
6174 2                         Check-Out          2017-09-01

## Question 3

**Q3.** Starting with the base data pipe to a filter to display bookings with at least one child or at least one baby. What command does this?

**A3.** The below command filters the base data to the desired subset. This filter focuses in on the 9332 observed bookings which are for more than just adults.

In [5]:
hotels %>%
  filter(children >= 1 | babies >= 1)

     hotel        is_canceled lead_time arrival_date_year arrival_date_month
1    Resort Hotel 0            18       2015              July
2    Resort Hotel 1            47       2015              July
3    Resort Hotel 0             1       2015              July
4    Resort Hotel 0            10       2015              July
5    Resort Hotel 1            79       2015              July
6    Resort Hotel 0           101       2015              July
7    Resort Hotel 0            92       2015              July
8    Resort Hotel 1            26       2015              July
9    Resort Hotel 0           102       2015              July
10   Resort Hotel 0            78       2015              July
11   Resort Hotel 0            79       2015              July
12   Resort Hotel 0             2       2015              July
13   Resort Hotel 0           109       2015              July
14   Resort Hotel 1            34       2015              July
15   Resort Hotel 0            97       2015              July
16   Resort Hotel 0             8       2015              July
17   Resort Hotel 0           115       2015              July
18   Resort Hotel 0            81       2015              July
19   Resort Hotel 0            84       2015              July
20   Resort Hotel 0             2       2015              July
21   Resort Hotel 0            68       2015              July
22   Resort Hotel 0            21       2015              July
23   Resort Hotel 0             8       2015              July
24   Resort Hotel 1           280       2015              July
25   Resort Hotel 0            17       2015              July
26   Resort Hotel 0            12       2015              July
27   Resort Hotel 1            24       2015              July
28   Resort Hotel 1            44       2015              July
29   Resort Hotel 0            78       2015              July
30   Resort Hotel 0            13       2015              July
⋮    ⋮            ⋮           ⋮         ⋮                 ⋮
9303 City Hotel   0            61       2017              August
9304 City Hotel   0            35       2017              August
9305 City Hotel   0             8       2017              August
9306 City Hotel   0           301       2017              August
9307 City Hotel   0             0       2017              August
9308 City Hotel   0           221       2017              August
9309 City Hotel   0            14       2017              August
9310 City Hotel   0            16       2017              August
9311 City Hotel   0             0       2017              August
9312 City Hotel   0           202       2017              August
9313 City Hotel   0           240       2017              August
9314 City Hotel   0           130       2017              August
9315 City Hotel   0           216       2017              August
9316 City Hotel   0           323       2017              August
9317 City Hotel   0             5       2017              August
9318 City Hotel   0             0       2017              August
9319 City Hotel   0            29       2017              August
9320 City Hotel   0            22       2017              August
9321 City Hotel   0           171       2017              August
9322 City Hotel   0           175       2017              August
9323 City Hotel   0             6       2017              August
9324 City Hotel   0           341       2017              August
9325 City Hotel   0           140       2017              August
9326 City Hotel   0           140       2017              August
9327 City Hotel   0             9       2017              August
9328 City Hotel   0             0       2017              August
9329 City Hotel   0           167       2017              August
9330 City Hotel   0           243       2017              August
9331 City Hotel   0           160       2017              August
9332 City Hotel   0            45       2017              August
     arrival_date_week_number arrival_date_day_of_month stays_in_weekend_nights
1    27                        1                        0
2    27                        2                        2
3    27                        2                        0
4    27                        3                        0
5    27                        3                        6
6    27                        3                        2
7    27                        4                        2
8    27                        4                        2
9    27                        4                        2
10   27                        4                        2
11   27                        4                        4
12   27                        4                        0
13   28                        5                        2
14   28                        5                        2
15   28                        5                        2
16   28                        5                        4
17   28                        6                        1
18   28                        6                        1
19   28                        6                        1
20   28                        6                        1
21   28                        6                        2
22   28                        7                        0
23   28                        7                        0
24   28                        8                        2
25   28                        9                        0
26   28                        9                        0
27   28                        9                        0
28   28                        9                        0
29   28                        9                        0
30   28                       10                        0
⋮    ⋮                        ⋮                         ⋮
9303 35                       27                        1
9304 34                       26                        2
9305 34                       26                        2
9306 35                       27                        2
9307 35                       29                        0
9308 34                       26                        2
9309 34                       24                        2
9310 34                       26                        2
9311 35                       28                        1
9312 34                       26                        2
9313 35                       28                        1
9314 34                       23                        2
9315 34                       26                        2
9316 35                       29                        0
9317 35                       29                        0
9318 35                       29                        0
9319 35                       27                        2
9320 35                       30                        0
9321 34                       22                        2
9322 35                       27                        2
9323 35                       28                        1
9324 35                       27                        2
9325 35                       27                        2
9326 35                       27                        2
9327 35                       28                        1
9328 35                       29                        0
9329 35                       27                        2
9330 35                       30                        0
9331 35                       29                        0
9332 35                       28                        1
     stays_in_week_nights adults ⋯ deposit_type agent company
1     4                   2      ⋯ No Deposit   241   NULL
2     5                   2      ⋯ No Deposit   240   NULL
3     1                   2      ⋯ No Deposit   NULL  NULL
4     2                   2      ⋯ No Deposit   240   NULL
5    15                   2      ⋯ No Deposit   242   NULL
6     5                   2      ⋯ No Deposit   240   NULL
7     4                   1      ⋯ No Deposit   241   NULL
8     5                   2      ⋯ No Deposit   240   NULL
9     5                   2      ⋯ No Deposit   240   NULL
10    5                   2      ⋯ No Deposit   240   NULL
11    6                   2      ⋯ No Deposit   250   NULL
12    1                   2      ⋯ No Deposit   240   NULL
13    3                   2      ⋯ No Deposit   241   NULL
14    4                   2      ⋯ No Deposit   240   NULL
15    5                   2      ⋯ No Deposit   250   NULL
16    5                   2      ⋯ No Deposit   240   NULL
17    4                   2      ⋯ No Deposit   240   NULL
18    3                   2      ⋯ No Deposit   250   NULL
19    3                   2      ⋯ No Deposit   240   NULL
20    0                   2      ⋯ No Deposit   NULL  NULL
21    5                   2      ⋯ No Deposit   240   NULL
22    3                   2      ⋯ No Deposit   250   NULL
23    4                   3      ⋯ No Deposit   240   NULL
24    5                   2      ⋯ No Deposit   40    NULL
25    1                   2      ⋯ No Deposit   242   NULL
26    2                   2      ⋯ No Deposit   NULL  NULL
27    3                   2      ⋯ No Deposit   242   NULL
28    3                   2      ⋯ No Deposit   240   NULL
29    3                   2      ⋯ No Deposit   240   NULL
30    2                   2      ⋯ No Deposit   240   NULL
⋮    ⋮                    ⋮      ⋱ ⋮            ⋮     ⋮
9303 0                    2      ⋯ No Deposit   85    NULL
9304 1                    2      ⋯ No Deposit   14    NULL
9305 1                    2      ⋯ No Deposit   7     NULL
9306 0                    2      ⋯ No Deposit   9     NULL
9307 1                    2      ⋯ No Deposit   229   NULL
9308 1                    2      ⋯ No Deposit   9     NULL
9309 3                    2      ⋯ No Deposit   9     NULL
9310 1                    2      ⋯ No Deposit   9     NULL
9311 0                    2      ⋯ No Deposit   14    NULL
9312 2                    1      ⋯ No Deposit   9     NULL
9313 1                    2      ⋯ No Deposit   9     NULL
9314 5                    2      ⋯ No Deposit   14    NULL
9315 2                    2      ⋯ No Deposit   11    NULL
9316 1                    2      ⋯ No Deposit   9     NULL
9317 1                    2      ⋯ No Deposit   9     NULL
9318 1                    2      ⋯ No Deposit   NULL  NULL
9319 1                    2      ⋯ No Deposit   9     NULL
9320 3                    2      ⋯ No Deposit   9     NULL
9321 7                    2      ⋯ No Deposit   14    NULL
9322 2                    1      ⋯ No Deposit   9     NULL
9323 3                    2      ⋯ No Deposit   7     NULL
9324 3                    2      ⋯ No Deposit   22    NULL
9325 3                    2      ⋯ No Deposit   9     NULL
9326 3                    2      ⋯ No Deposit   9     NULL
9327 3                    2      ⋯ No Deposit   14    NULL
9328 3                    2      ⋯ No Deposit   9     NULL
9329 4                    2      ⋯ No Deposit   9     NULL
9330 3                    2      ⋯ No Deposit   9     NULL
9331 5                    2      ⋯ No Deposit   9     NULL
9332 5                    2      ⋯ No Deposit   7     NULL
     days_in_waiting_list customer_type adr    required_car_parking_spaces
1    0                    Transient     154.77 0
2    0                    Transient     153.00 0
3    0                    Transient     107.00 1
4    0                    Transient     153.00 1
5    0                    Transient     108.73 0
6    0                    Transient      99.30 1
7    0                    Transient      96.49 0
8    0                    Transient     163.00 0
9    0                    Transient      73.80 0
10   0                    Transient     139.00 0
11   0                    Transient     149.00 0
12   0                    Transient     163.00 1
13   0                    Transient      85.59 1
14   0                    Transient     163.00 0
15   0                    Transient     164.20 1
16   0                    Transient     175.00 1
17   0                    Transient     167.00 0
18   0                    Transient     210.00 1
19   0                    Transient      97.00 0
20   0                    Transient     131.00 0
21   0                    Transient     185.00 0
22   0                    Transient     185.50 0
23   0                    Transient     193.00 0
24   0                    Contract      112.00 0
25   0                    Transient     123.00 0
26   0                    Transient     146.00 1
27   0                    Transient     123.00 0
28   0                    Transient     153.00 0
29   0                    Transient      82.00 0
30   0                    Transient     185.00 1
⋮    ⋮                    ⋮             ⋮      ⋮
9303 0                    Transient      90.60 0
9304 0                    Transient     176.64 0
9305 0                    Transient     253.51 0
9306 0                    Transient     179.10 0
9307 0                    Group         270.00 0
9308 0                    Transient     198.00 0
9309 0                    Transient     165.60 0
9310 0                    Transient     126.00 0
9311 0                    Transient     150.00 0
9312 0                    Transient     117.00 0
9313 0                    Transient     135.00 0
9314 0                    Transient     300.00 0
9315 0                    Transient      93.60 0
9316 0                    Transient     125.10 0
9317 0                    Transient     259.00 0
9318 0                    Transient     270.00 0
9319 0                    Transient     233.00 0
9320 0                    Transient      61.80 0
9321 0                    Transient     180.00 0
9322 0                    Transient     175.50 0
9323 0                    Transient     190.00 0
9324 0                    Transient      96.91 0
9325 0                    Transient     235.00 0
9326 0                    Transient     235.00 0
9327 0                    Transient     210.00 0
9328 0                    Transient     135.00 0
9329 0                    Transient     177.75 0
9330 0                    Transient     189.00 0
9331 0                    Transient     153.90 0
9332 0                    Transient     194.13 0
     total_of_special_requests reservation_status reservation_status_date
1    1                         Check-Out          2015-07-05
2    0                         Canceled           2015-06-02
3    2                         Check-Out          2015-07-03
4    0                         Check-Out          2015-07-05
5    2                         Canceled           2015-04-15
6    2                         Check-Out          2015-07-10
7    2                         Check-Out          2015-07-10
8    0                         Canceled           2015-06-09
9    2                         Check-Out          2015-07-11
10   2                         Check-Out          2015-07-11
11   1                         Check-Out          2015-07-14
12   0                         Check-Out          2015-07-05
13   2                         Check-Out          2015-07-10
14   0                         Canceled           2015-06-17
15   1                         Check-Out          2015-07-12
16   1                         Check-Out          2015-07-14
17   0                         Check-Out          2015-07-11
18   0                         Check-Out          2015-07-10
19   2                         Check-Out          2015-07-10
20   0                         Check-Out          2015-07-07
21   0                         Check-Out          2015-07-13
22   1                         Check-Out          2015-07-10
23   1                         Check-Out          2015-07-11
24   1                         Canceled           2015-04-15
25   3                         Check-Out          2015-07-10
26   0                         Check-Out          2015-07-11
27   1                         Canceled           2015-06-16
28   0                         Canceled           2015-06-16
29   2                         Check-Out          2015-07-12
30   1                         Check-Out          2015-07-12
⋮    ⋮                         ⋮                  ⋮
9303 1                         Check-Out          2017-08-28
9304 1                         Check-Out          2017-08-29
9305 2                         Check-Out          2017-08-29
9306 0                         Check-Out          2017-08-29
9307 1                         Check-Out          2017-08-30
9308 1                         Check-Out          2017-08-29
9309 2                         Check-Out          2017-08-29
9310 2                         Check-Out          2017-08-29
9311 0                         Check-Out          2017-08-29
9312 0                         Check-Out          2017-08-30
9313 3                         Check-Out          2017-08-30
9314 1                         Check-Out          2017-08-30
9315 0                         Check-Out          2017-08-30
9316 2                         Check-Out          2017-08-30
9317 0                         Check-Out          2017-08-30
9318 0                         Check-Out          2017-08-30
9319 0                         Check-Out          2017-08-30
9320 0                         Check-Out          2017-09-02
9321 1                         Check-Out          2017-08-31
9322 1                         Check-Out          2017-08-31
9323 1                         Check-Out          2017-09-01
9324 1                         Check-Out          2017-09-01
9325 0                         Check-Out          2017-09-01
9326 0                         Check-Out          2017-09-01
9327 0                         Check-Out          2017-09-01
9328 2                         Check-Out          2017-09-01
9329 0                         Check-Out          2017-09-02
9330 3                         Check-Out          2017-09-02
9331 0                         Check-Out          2017-09-03
9332 1                         Check-Out          2017-09-03

## Questions 4, 5, 6, 7

**Q4.** Do you think it's more likely to find bookings with children or babies in city hotels or resort hotels?

**A4.** I think it's more likely to find bookings with children or babies in resort hotels, because I expect families looking for vacations to go for resorts more often than cities, and I think vacations would be the most common reason for children or babies to be staying at a hotel.

**Q5.** Determine the number of bookings in resort hotels that have more than one child or one baby in the room. What command does this?

**A5.** There are *3929* bookings in *resort* hotels that fit the description. The below command shows this number.

**Q6.** Then do the same for city hotels. What command does this?

**A6.** There are *5403* bookings in *city* hotels that fit the description. The same below command also shows this number.

**Q7.** Compare the numbers of rows in the resulting filtered data frames. Where do you find bookings with children or babies in city hotels or resort hotels?

**A7.** There are more bookings with children or babies in city hotels than resort hotels (the opposite of my prediction).

In [14]:
hotels %>%
  filter(children >= 1 | babies >= 1) %>%
  count(hotel)

  hotel        n
1 City Hotel   5403
2 Resort Hotel 3929

## Question 8

**Q8.** Create a frequency table of the number of `adults` in a booking. Display the results in descending order so the most common observation is on top. What is the most common number of adults in bookings in this dataset? Are there any surprising results?

**A8.** The most common number of adults in bookings in this dataset is 2, both for city and resort hotels individually and together, which is not very surprising. What is somewhat surprising is the 223 bookings in city hotels with at least one child or baby but no adults.

In [16]:
hotels %>%
  filter(children >= 1 | babies >= 1) %>%
  count(hotel, adults, sort = TRUE)

  hotel        adults n
1 City Hotel   2      4729
2 Resort Hotel 2      3391
3 Resort Hotel 3       400
4 City Hotel   1       315
5 City Hotel   0       223
6 City Hotel   3       136
7 Resort Hotel 1       135
8 Resort Hotel 4         3

## Question 9

**Q9.** Repeat the above exercise once for canceled bookings (`is_canceled` coded as 1) and once for not canceled bookings (`is_canceled` coded as 0). What does this reveal about the surprising results you spotted in the previous exercise?

**A9.** Booking with no adults were proportionally more often cancelled.

In [17]:
hotels %>%
  filter(is_canceled == 1, children >= 1 | babies >= 1) %>%
  count(hotel, adults, sort = TRUE)

  hotel        adults n
1 City Hotel   2      1666
2 Resort Hotel 2      1168
3 Resort Hotel 3       191
4 City Hotel   0        84
5 City Hotel   1        82
6 Resort Hotel 1        37
7 City Hotel   3        30
8 Resort Hotel 4         1

In [18]:
hotels %>%
  filter(is_canceled == 0, children >= 1 | babies >= 1) %>%
  count(hotel, adults, sort = TRUE)

  hotel        adults n
1 City Hotel   2      3063
2 Resort Hotel 2      2223
3 City Hotel   1       233
4 Resort Hotel 3       209
5 City Hotel   0       139
6 City Hotel   3       106
7 Resort Hotel 1        98
8 Resort Hotel 4         2

## Questions 10, 11

**Q10.** Calculate minimum, mean, median, and maximum average daily rate (`adr`) grouped by `hotel` type so that you can get these statistics separately for resort and city hotels. Which type of hotel is higher, on average?

**A10.** On average, city hotels have a higher adr than resort hotels.

**Q11.** We observe two unusual values in the summary statistics above -- a negative minimum, and a very high maximum. What types of hotels are these?

**A11.** The negative minimum adr comes from a resort hotel. The very high maximum adr comes from a city hotel.

In [19]:
hotels %>%
  group_by(hotel) %>%
  summarize(min_adr = min(adr), max_adr = max(adr), mean_adr = mean(adr), median_adr = median(adr))

  hotel        min_adr max_adr mean_adr  median_adr
1 City Hotel    0.00   5400    105.30447 99.9
2 Resort Hotel -6.38    508     94.95293 75.0

## Question 12

**Q12.** Locate these observations in the dataset and find out the arrival date (year and month) as well as how many people (adults, children, and babies) stayed in the room. You can investigate the data in the viewer to locate these values, but preferably you should identify them in a reproducible way with some code. *Hint: You can `filter` for the given `adr` amounts and `select` the relevant columns.*

**A12.** The resort hotel booking with a -6.38 adr was for just 2 adults in March of 2017. The city hotel booking with a 5400 adr was for just 2 adults in March of 2016.

In [24]:
hotels %>%
  filter(adr == -6.38 | adr == 5400) %>%
  select(hotel, adr, arrival_date_year, arrival_date_month, adults, children, babies)

  hotel        adr     arrival_date_year arrival_date_month adults children
1 Resort Hotel   -6.38 2017              March              2      0
2 City Hotel   5400.00 2016              March              2      0
  babies
1 0
2 0